### ISSUE TITLE
Customized doneButtonChild is not implemented in story_maker: 1.0.3

### ISSUE THREAD

**Issue by wilz05** [NarekManukyan/story_maker#1]
Thank you so much for the package. 

below code has not been called/implemented in current version 1.0.3

`doneButtonChild` widget hasn't been added in 
```
FooterToolsWidget(
                onDone: _onDone,
   )
```
Customizing "Add to Story" button is not working.

**Comment by NarekManukyan** [comment]
@wilz05 Thanks. I'm still working on it. Will be in the next version.

**Comment by wilz05** [comment]
@NarekManukyan oh Okay, thank you for the quick response.
  If you could add 2 more options that would be good (Suggestions)

1. Adding more font names for google fonts.  along with static title 
example  [{title : 'Aa' , fontNames : ['Sen','Armata'....]}, 
{title : 'لب' , fontNames : ['Noto Serif Korean','Serif'....]} ]
```
             Text(
                    'Aa',
                    style: GoogleFonts.getFont(
                      fontFamilyList[index],
                    )
```

 If null current default list. i.e fontFamilyList

2. Passing optional image types ui.ImageByteFormat.png = ImageType : Png or Jpg.

**Comment by NarekManukyan** [comment]
@wilz05 Good suggestions. Thanks

**Comment by NarekManukyan** [comment]
@wilz05 Sorry for such a late reply. The problem has been fixed. I'll work on suggestions later.
