### ISSUE TITLE
Cannot open the StoryMaker more than once - why static GlobalKey?

### ISSUE THREAD

**Issue by AleksandarSavic95** [NarekManukyan/story_maker#2]
Hello author of StoryMaker!

When trying to open the StoryMaker screen the second time (I create one story, and then I want to navigate to StoryMaker again), I get an exception:
<img src="https://user-images.githubusercontent.com/12213798/166959781-873efaf7-e73c-47a6-9cea-ac0f739072ec.png" width="400"/>
```dart
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3888 pos 12: 'element._lifecycleState == _ElementLifecycle.inactive': is not true.
package:flutter/…/widgets/framework.dart:3888
The relevant error-causing widget was
StoryMaker
```

After modifying the source code to remove the `static` keyword, the StoryMaker screen can be opened again.
Why is the GlobalKey `static`?

https://github.com/NarekManukyan/story_maker/blob/079fd310844219fb9bb8fb28ebced4c8d9454899/lib/story_maker.dart#L46

**Comment by NarekManukyan** [comment]
Hi @AleksandarSavic95 .
Thanks for reporting. Will fix it.

**Comment by AleksandarSavic95** [comment]
@NarekManukyan hello
any updates on this?

**Comment by AleksandarSavic95** [comment]
@NarekManukyan when are you gonna merge this?

**Comment by NarekManukyan** [comment]
@AleksandarSavic95 Sorry for such a late reply. The problem has been fixed.
