### ISSUE TITLE
The version of Google Fonts Package is old

### ISSUE THREAD

**Issue by ghost** [NarekManukyan/story_maker#5]
../../.pub-cache/hosted/pub.dev/google_fonts-3.0.1/lib/src/google_fonts_base.dart:14:1: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
import 'asset_manifest.dart';
^^^^^^^^^^^^^

**Comment by NarekManukyan** [comment]
Hi @ahmeedgad . PR is welcome 😊

**Comment by NarekManukyan** [comment]
Resolved in version 1.0.5
